### ISSUE TITLE
CD: should a test failure of pushed reference block publishing procedures?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#317]
We recently [experienced a failure to push](https://travis-ci.org/github/jupyterhub/zero-to-jupyterhub-k8s/builds/709161151) the 0.9.1 tag of z2jh due to a test failed. So I'd like to discuss general practices to have in the CI publishing procedures of our repos so we can align with what we conclude.

## master pushes
- Should we typically publish directly or do it conditionally by running tests first?

## tag pushes
- Should we typically publish directly or do it conditionally by running tests first?

@minrk wrote that tests should never block releases from tags. I think that makes a lot of sense, but I've also considered pushes to master for the z2jh repo for example and is less confident about it but lean towards we should always publish whatever is pushed to master or whatever commit is tagged in our CI/CD pipelines.

__NOTE:__ I excluded the option to run tests optionally on pushes to master or tags. This was because I think it's hard to implement in Travis and not worth the effort or added complexity to maintain.

## Repositories updated

In `.travis.yml` we can configure conditionals for the stages themselves, outside the job definitions. Like this for example.

```yaml
# Don't run tests if triggered by a tag that was pushed
stages:
  - name: test
    if: tag IS NOT present
  - name: publish
    if: tag IS present
```

Noteworthy is also that if you have a publish job and have some common `script` blocks etc where you run tests, you must override them in the publish job as well. Like this for example, note that overriding it to `[]` will not be sufficient, it will just be ignored!

```yaml
jobs:
  include:
    - stage: publish
      script:
        - echo "Required dummy override of default 'script' in .travis.yml."
      after_success:
        - echo "Required dummy override of default 'after_success' in .travis.yml."
```

- I've updated Kubespawner like above in https://github.com/jupyterhub/kubespawner/pull/417
- I've updated chartpress like above in https://github.com/jupyterhub/chartpress/pull/95
