### ISSUE TITLE
Systematic re-configuration of dependabot to update github actions monthly

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#636]
In the [January team meeting](https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/community/2023-01-17.html#agenda-items) we decided to transition from daily/weekly updates to monthly updates of github actions.

I'll open PRs to reconfigure dependabot in all our repositories and reference this issue to centralize any discussion.

### Planned dependabot entry

```yaml
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
```

### Related - a decision about labels?

There are some github repositories that configure dependabot to set labels on these updates, but we are not consistent about that. Since making all these PRs is a bit of a chore, I'd like to ask if we should while doing it standardize the labels we set on the PRs when bumping the github actions specifically.

If we set a label at all, it could for example be "maintenance", "dependencies", or "ci". I'm not strongly opinionated now that we reduce the frequency to monthly, but I'm leaning towards thinking the ci label is good for this to avoid cluttering the "maintenance" part of the `github-activity` generated changelog. I've used the "ci" label to label changes to github workflows etc that doesn't change the repositorys main code (helm chart templates, python code, etc.), and "maintenance" for anything that does.

**Question: it okay that I also configre "ci" as a label systematically like below?**

```yaml
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
```

### Related - consistently name the file dependabot.yaml (instead of .yml)?

I wen't for it and updated the PRs not merged and added 3 PRs to update already merged PRs with this rename from .yml to .yaml. I think about half of the repos were using .yml and .yaml respectively.

There is no real benefit to having either .yaml or .yml, both works - I have a preference of sticking to one option, and preferably also with .yaml because thats what almost all other YAML files are in helm charts etc.

### Repositories with dependabot bumping github actions

- https://github.com/jupyterhub/jupyterhub/pull/4403
- https://github.com/jupyterhub/binderhub/pull/1651
- https://github.com/jupyterhub/nativeauthenticator/pull/233
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3085
- https://github.com/jupyterhub/traefik-proxy/pull/201
- https://github.com/jupyterhub/oauthenticator/pull/588
- https://github.com/jupyterhub/configurable-http-proxy/pull/474
- https://github.com/jupyterhub/pebble-helm-chart/pull/25
- https://github.com/jupyterhub/action-k8s-await-workloads/pull/61
- https://github.com/jupyterhub/gh-scoped-creds/pull/46
- https://github.com/jupyterhub/kubespawner/pull/713
- https://github.com/jupyterhub/nbgitpuller/pull/299
- https://github.com/jupyterhub/docker-image-cleaner/pull/115
- https://github.com/jupyterhub/repo2docker/pull/1262
- https://github.com/jupyterhub/simpervisor/pull/28
- https://github.com/jupyterhub/the-littlest-jupyterhub/pull/871
- https://github.com/jupyterhub/action-k3s-helm/pull/92
- https://github.com/jupyterhub/action-major-minor-tag-calculator/pull/294
- https://github.com/jupyterhub/ltiauthenticator/pull/148
- https://github.com/jupyterhub/outreachy/pull/193
- https://github.com/jupyterhub/mybinder.org-deploy/pull/2546
- https://github.com/jupyterhub/autodoc-traits/pull/43
- https://github.com/jupyterhub/chartpress/pull/213
- https://github.com/jupyterhub/action-k8s-namespace-report/pull/21
- https://github.com/jupyterhub/jupyterhub-deploy-docker/pull/123
- https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/30
- https://github.com/jupyterhub/pytest-jupyterhub/pull/50
- https://github.com/jupyterhub/jupyter-server-proxy/pull/385
